### ISSUE TITLE
Any interest in breaking out some of this crates functionality into a general purpose docker client api?

### ISSUE THREAD

**Issue by TheButlah** [testcontainers/testcontainers-rs#204] opened 2020-09-10 19:40 UTC
I'm fairly unfamiliar with Rust's options for docker clients, but from what I can see based on a cursory search of crates.io, I think this library's api is a lot more ergonomic than the alternatives out there. I know that this crate is not intended for production use or use outside of integration tests, but is there any code that could be extracted into another crate and used as the start of a general purpose docker client library? Any thoughts on what that might look like?

**Comment by thomaseizinger** [comment] 2020-09-11 02:07
Initially when I created this lib, I didn't think that we would be stuck with a `docker` CLI based client for this long :D

I actually intend to at some point switch over to a HTTP-based one to allow for greater flexibility and also async support.

Generally, I don't think the code in this crate is a good candidate for being extracted:

1. It is very minimal, and could easily be reproduced if you need a simple client.
2. There is no error handling. We have lots of unwraps everywhere which is really only possible because we only want to be used in tests. This is unacceptable for any kind of production code that needs to interact with docker.

I would actually like to go the other way round: Replace the CLI client with a proper HTTP client. Options I know of:

- https://github.com/softprops/shiplift
- https://github.com/fussybeaver/bollard

**Comment by ywalterh** [comment] 2020-09-28 22:16
Moving to HTTP client definitely would make features like exposing host Docker daemon is running on much easier. But it'll change the way testcontainers framework starts up. Mac / Linux uses unix socket and Windows don't. Docker binary is a good abstraction to dodge these problems. But for long term I believe it's a worthwhile change. 

I had some experience porting CLI lib to native Docker API. I can take a stab at it using either shiplift / bollard. (Or report back neither are feature complete). After the change:

- Only Mac / Linux would have good unix socket default 
- Windows and remote docker host would need to provide Host / Port either via code level API or DOCKER_HOTS env
- Features depending `docker cp` and `docker log` might require extra work in the library to handle

Let me know if I can help.

**Comment by thomaseizinger** [comment] 2020-09-29 02:07
> I had some experience porting CLI lib to native Docker API. I can take a stab at it using either shiplift / bollard. (Or report back neither are feature complete). After the change:
> - Only Mac / Linux would have good unix socket default 
> - Windows and remote docker host would need to provide Host / Port either via code level API or DOCKER_HOTS env
> - Features depending `docker cp` and `docker log` might require extra work in the library to handle

I've worked with `shiplift` in the past and it has [some code](https://github.com/softprops/shiplift/blob/49afd94f8d084ac028920c1785b2ddb05c13bef3/src/lib.rs#L903-L949) already that makes cross-platform usage easier. Not sure how much that evolved though, it was still a bit of a pain to get it working, especially on windows :(

Also, I think recent versions of Docker for Windows have a "named-pipe" feature that is similar to unix sockets. Not sure how well that works though and if it would be concern for us. Generally, I would hope that all this trickery would be abstracted away by a good docker client lib :)

> Let me know if I can help.

I would definitely appreciate some help on this front! If you are keen, feel free to give it a go :)

**Comment by ywalterh** [comment] 2020-09-29 02:17
Thanks for all the additional info @thomaseizinger. I'll take it for a spin then.

**Comment by thomaseizinger** [comment] 2020-11-16 23:35
Closing this because the original question has been answered!

**Closed by thomaseizinger** 2020-11-16 23:35 UTC
