### ISSUE TITLE
Problem mounting volumes after revamp

### ISSUE THREAD

**Issue by ns-sjorgedeaguiar** [testcontainers/testcontainers-rs#580] opened 2024-04-23 01:30 UTC
Hi, I was testing the new version after #575 and mounting is not working with custom images.

The problem seems to be because the runner sets the [`volumes`](https://github.com/testcontainers/testcontainers-rs/blob/d0799346adb6dc63d50d78f4327391c6ca4edf89/testcontainers/src/runners/async_runner.rs#L97-L102) config option:
```rust
// volumes
let vols: HashMap<String, HashMap<(), ()>> = runnable_image
    .volumes()
    .map(|(orig, dest)| (format!("{orig}:{dest}"), HashMap::new()))
    .collect();
config.volumes = Some(vols);
```

However that option is meant for anonymous volume mounts, where the keys are the path inside the container and the values are [an empty map](https://github.com/fussybeaver/bollard/blob/907037dd9b0d2a23d7224b06d4b37e9fe99af448/src/container.rs#L198-L201).
The `binds` hostconfig option is the one accepting a [list of mounts](https://github.com/fussybeaver/bollard/blob/907037dd9b0d2a23d7224b06d4b37e9fe99af448/codegen/swagger/src/models.rs#L2560-L2563). Replacing the above by something like this works:
```rust
// volumes
let binds: Vec<String> = runnable_image
    .volumes()
    .map(|(orig, dest)| format!("{orig}:{dest}"))
    .collect();
if !binds.is_empty() {
    config.host_config = config.host_config.map(|mut host_config| {
        host_config.binds = Some(binds);
        host_config
    });
}
```

**Comment by DDtKey** [comment] 2024-04-23 01:39
Thanks for reporting!

Yeah, this should be fixed.

Interestingly, no one has used an http client with volumes before (that part hasn't actually been changed).
Anyway, the issue is pretty straightforward. 

Feel free to open PR if you wish

**Closed** 2024-04-23 08:27 UTC
