### ISSUE TITLE
"hyper legacy client error" when starting any container

### ISSUE THREAD

**Issue by martin-walls** [testcontainers/testcontainers-rs#625] opened 2024-05-07 13:10 UTC
When attempting to start any container, I always get the same error:
```
thread 'db::tests::test_connect_to_db' panicked at /home/martin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/testcontainers-0.16.7/src/runners/async_runner.rs:204:29:
Error in the hyper legacy client: client error (Connect)
```

I tried using `GenericImage` exactly as shown in the documentation, and I also tried modules from testcontainers-modules.

Searching for the error brought up no results.

**Comment by DDtKey** [comment] 2024-05-07 13:53
Hi there!

Couple of questions:
- what OS do you use?
- Do you have `DOCKER_HOST` set ?

**Comment by martin-walls** [comment] 2024-05-07 14:09
OS: Fedora 38

`DOCKER_HOST` is not set.

**Comment by DDtKey** [comment] 2024-05-07 16:45
Can't reproduce

Could you enable `RUST_BACKTRACE=1` and also would be nice to enable debug logging (you can use something simple, like https://github.com/testcontainers/testcontainers-rs/blob/476f0df2afae88b219621754e0dbd1301fa94bfc/testcontainers/tests/sync_runner.rs#L35)

**Comment by martin-walls** [comment] 2024-05-08 07:51
Ah yes, thanks, for some reason my docker installation put the socket at `~/.docker/desktop/docker.sock` instead of `/var/run/docker/sock`, so it was trying to connect to a non-existent socket.

Setting `DOCKER_HOST` to the correct path makes it work.

**Comment by DDtKey** [comment] 2024-05-08 16:14
I'm glad I could help!

In that case I'm going to close the issue if you don't mind.

**Closed** 2024-05-08 16:15 UTC
Labels: question
