### ISSUE TITLE
Create containers per test or as a static global?

### ISSUE THREAD

**Issue by feelingsonice** [testcontainers/testcontainers-rs#745] opened 2024-09-30 22:28 UTC
Kind of related to my previous issue here https://github.com/testcontainers/testcontainers-rs/issues/727#issuecomment-2334720253

When I use `testcontainers` and create a new container for **every** tests, I often run into some issue where some of the containers aren't successfully created (maybe a race condition). So then my instinct told me to create a static global container with something like this for the test module:

```rust
    // Static variables for Redis container and URL
    static REDIS_CONTAINER: OnceCell<ContainerAsync<GenericImage>> = OnceCell::const_new();
    static REDIS_URL: OnceCell<String> = OnceCell::const_new();

    // Function to initialize and get the Redis container
    async fn get_redis() -> &'static ContainerAsync<GenericImage> {
        REDIS_CONTAINER
            .get_or_init(|| async {
                GenericImage::new("redis", "7.4")
                    .with_exposed_port(6379.tcp())
                    .start()
                    .await
                    .expect("Redis test container failed to start")
            })
            .await
    }

    // Function to get the Redis URL
    async fn get_redis_url() -> &'static str {
        REDIS_URL
            .get_or_init(|| async {
                let container = get_redis().await;
                let host_port = container
                    .get_host_port_ipv4(6379)
                    .await
                    .expect("Failed to get host port");
                format!("redis://127.0.0.1:{}", host_port)
            })
            .await
    }
```

This worked for a while but I soon realized that the clean up of these containers often fail. That is, I'm often left with something like this after a bit of development:

<img width="1025" alt="Screenshot 2024-09-30 at 3 25 42 PM" src="https://github.com/user-attachments/assets/0652a3c2-829b-4c06-bcc8-54ef677294a4">

So far I have the `watchdog` feature enabled but this is still happening. I guess my question is, what's the recommended approach here? Is there one or is this a current limitation?

**Comment by DDtKey** [comment] 2024-09-30 23:14
Hi there 👋 

Sorry, but this is duplicate of #577 and #707. 

In #707 you can find some workaround how to achieve this even right now, for example: https://github.com/testcontainers/testcontainers-rs/issues/707#issuecomment-2248314261


Closing due to this

**Closed by DDtKey** 2024-09-30 23:14 UTC

**Comment by feelingsonice** [comment] 2024-09-30 23:20
@DDtKey Maybe I should rename the issue, but I dont think the suggested workaround in https://github.com/testcontainers/testcontainers-rs/issues/707#issuecomment-2248314261 is any different from what I have above?

I guess I'm not asking for "how to create a single global container", the problem I'm experiencing is that the containers still aren't shut down properly...? I have the `watchdog` feature enabled.

**Comment by DDtKey** [comment] 2024-09-30 23:22
They are different, take a look at the `Weak` usage
